name: CI-beta

on:
  push:
    branches: [ main-beta ]
  pull_request:
    branches: [ main-beta ]
env:
  DEVELOPER_DIR: /Applications/Xcode_12_beta.app/Contents/Developer

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Generate Xcode project
      run: swift package generate-xcodeproj
    - name: Build and Test (with code coverage)
      run: xcodebuild -project FioriSwiftUI.xcodeproj -scheme FioriSwiftUI-Package -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11' build test
